spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: aa1237113

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  devtools:
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    generate-ddl: true
    show-sql: true

